---
title: "Selecting_Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Note: Need to read in the data with `tidyverse` as that is the only way to make it availabe when knitting R markdown to HTML
library(tidyverse)
zillow_oc_2017 <- read_csv(file="../../02-Evr_Read_CSV/Resources/zillow_orange_county_2017.csv")
```

### Use bracket `[]` notation to select specific rows and columns by number, range, name, or vector
### Row Index Number, Column Index Number

```{r}
zillow_oc_2017[1,1]
```

### Row Index Number, Column Name

```{r}
zillow_oc_2017[1,'parcelid']
```

### Row Index Number Range, Column Index Number Range

```{r}
zillow_oc_2017[1:2,1:14]
```

### Row Index Number Vector, Column Name Vector

```{r}
zillow_oc_2017[c(1, 10, 42),c('finishedsquarefeet', 'yearbuilt', 'homevalue')]
```

### Filter data by row 

```{r}
zillow_oc_sqft_gt_2000 <- zillow_oc_2017[deframe(zillow_oc_2017['finishedsquarefeet']) > 2000,]
```

### Check filtered data

```{r}
zillow_oc_sqft_gt_2000

```